### ISSUE TITLE
您好Zeghs

### ISSUE THREAD

**Issue by Paw2Pom** [Zeghs/ZeroSystem#1]
您好Zeghs, 我正在努力學習Ｃ#, 如果有機會的話不知道有沒有機會能向您上課學習coding呢? 非常感謝

**Comment by Paw2Pom** [comment]
不知道有審麼方式可以聯絡到您呢

**Comment by Zeghs** [comment]
上課不敢當, 可以互相討論學習, 這個是自動交易系統, 如果有興趣可自行下載修改


Paw2Pom ***@***.***> 於 2021年6月6日 週日 下午12:34寫道：

**Comment by Zeghs** [comment]
> 不知道有審麼方式可以聯絡到您呢

**Comment by Zeghs** [comment]
> 您好Zeghs, 我正在努力學習Ｃ#, 如果有機會的話不知道有沒有機會能向您上課學習coding呢? 非常感謝

上課不敢當, 可以互相討論學習, 這個是自動交易系統, 如果有興趣可自行下載修改
如果您需要 .NET 5.0 版本 也請告訴我, 目前 .NET 5.0 尚未上傳至 GitHub

**Comment by Paw2Pom** [comment]
好的非常希望能有機會一起討論學習. 我目前主要在學習powerlanguage, 但pl.net是之後的目標!

**Comment by Zeghs** [comment]
zeroSystem 本來也是按照PowerLanguage.NET 開發, 但是為了需要可以同時套利或是多點交易, 所以已經偏離原架構,
所以已經變成 PL.NET + C# 混和語言

CK ***@***.***> 於 2021年7月21日 週三 上午11:20寫道：
